#!/bin/bash

#Customize this for your application
APPLICATION_FILE_PATH=lacap

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/__PRODUCT__-__VERSION__
rm -rf /Applications/Lacap.app
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
cp -rf ${PRODUCT_HOME}/Lacap.app /Applications
cd ${PRODUCT_HOME}
./install.sh
echo "Post installation process finished"
